build: false

environment:
  PYTHONIOENCODING: "UTF-8"

  matrix:
    - PYTHON: "C:/Python27-x64"
    - PYTHON: "C:/Python34-x64"
    - PYTHON: "C:/Python35-x64"
    - PYTHON: "C:/Python36-x64"
    - PYTHON: "C:/Python37-x64"

install:
  - "python -m pip install --upgrade pip"
  - "pip install -r requirements.txt"

test_script:
  - "pytest -v"
